### ISSUE TITLE
Get Kia's AN email address working

### ISSUE THREAD

**Issue by tnicho1** [kiakatherine/adaptivenutrition#68]

**Comment by tnicho1** [comment]
- Prompt telling customer they will be taken to their meal plan immediately following purchase
- Add "in inches" after Height field
- Add "in lbs" after Weight
- Add "Approx" after BF%
- Add prompt telling customer to bookmark the address
- Add automated email to customer with link

**Comment by kiakatherine** [comment]
http://kb.mailchimp.com/campaigns/design/create-unique-campaign-urls-for-subscribers
